In [3]:
import pandas as pd

df1 = pd.DataFrame({
    "id": [1, 2, 3],
    "customer_id": [1, 2, 3],
    "customer_name": ["Robert", "Peter", "Dave"]
}, columns=["id", "customer_id", "customer_name"])
df1

   id  customer_id customer_name
0   1            1        Robert
1   2            2         Peter
2   3            3          Dave

In [4]:
df2 = pd.DataFrame({
    "id": [1, 2, 4],
    "order_id": [100, 200, 300],
    "order_date": ["2025-01-21", "2025-02-03", "2025-09-01"]
}, columns=["id", "order_id", "order_date"])
df2

   id  order_id  order_date
0   1       100  2025-01-21
1   2       200  2025-02-03
2   4       300  2025-09-01

In [ ]:
# 서로 다른 데이터 프레임을 하나로 합치는 방법

# 1) concat() : 서로 다른 데이터 프레임을 단순 연결 (*교차되는 특정 인덱스를 고려 x) -> 좌.우 & 상.하 (디폴트)
# 2) merge() : 특정 인덱스를 기준

In [5]:
pd.concat([df1, df2])

   id  customer_id customer_name  order_id  order_date
0   1          1.0        Robert       NaN         NaN
1   2          2.0         Peter       NaN         NaN
2   3          3.0          Dave       NaN         NaN
0   1          NaN           NaN     100.0  2025-01-21
1   2          NaN           NaN     200.0  2025-02-03
2   4          NaN           NaN     300.0  2025-09-01

In [6]:
doc = pd.concat([df1, df2], axis=1)
doc

   id  customer_id customer_name  id  order_id  order_date
0   1            1        Robert   1       100  2025-01-21
1   2            2         Peter   2       200  2025-02-03
2   3            3          Dave   4       300  2025-09-01

In [7]:
pd.merge(df1, df2) # merge() => inner JION 기능 유사

   id  customer_id customer_name  order_id  order_date
0   1            1        Robert       100  2025-01-21
1   2            2         Peter       200  2025-02-03

In [8]:
pd.merge(df1, df2, on="id")

   id  customer_id customer_name  order_id  order_date
0   1            1        Robert       100  2025-01-21
1   2            2         Peter       200  2025-02-03

In [18]:
pd.merge(df1, df2, on="id", how="inner")#inner생략 가능

   id  customer_id customer_name  order_id  order_date
0   1            1        Robert       100  2025-01-21
1   2            2         Peter       200  2025-02-03

In [17]:
pd.merge(df1, df2, on="id", how="outer")

   id  customer_id customer_name  order_id  order_date
0   1          1.0        Robert     100.0  2025-01-21
1   2          2.0         Peter     200.0  2025-02-03
2   3          3.0          Dave       NaN         NaN
3   4          NaN           NaN     300.0  2025-09-01

In [16]:
pd.merge(df1, df2, on="id", how="left")

   id  customer_id customer_name  order_id  order_date
0   1            1        Robert     100.0  2025-01-21
1   2            2         Peter     200.0  2025-02-03
2   3            3          Dave       NaN         NaN

In [15]:
pd.merge(df1, df2, on="id", how="right")

   id  customer_id customer_name  order_id  order_date
0   1          1.0        Robert       100  2025-01-21
1   2          2.0         Peter       200  2025-02-03
2   4          NaN           NaN       300  2025-09-01

In [19]:
df1 = df1.set_index("id")
df1

    customer_id customer_name
id
1             1        Robert
2             2         Peter
3             3          Dave

In [21]:
df2 = df2.set_index("id")
df2

    order_id  order_date
id
1        100  2025-01-21
2        200  2025-02-03
4        300  2025-09-01

In [22]:
pd.merge(df1, df2, left_index=True, right_index=True)

    customer_id customer_name  order_id  order_date
id
1             1        Robert       100  2025-01-21
2             2         Peter       200  2025-02-03

In [23]:
pd.merge(df1, df2, how="outer", left_index=True, right_index=True)

    customer_id customer_name  order_id  order_date
id
1           1.0        Robert     100.0  2025-01-21
2           2.0         Peter     200.0  2025-02-03
3           3.0          Dave       NaN         NaN
4           NaN           NaN     300.0  2025-09-01

In [24]:
pd.merge(df1, df2, how="right", left_index=True, right_index=True)

    customer_id customer_name  order_id  order_date
id
1           1.0        Robert       100  2025-01-21
2           2.0         Peter       200  2025-02-03
4           NaN           NaN       300  2025-09-01

In [26]:
df = pd.DataFrame({
    "영어": [60, 70],
    "수학": [100, 50]
}, columns=["영어", "수학"], index=["Dave", "David"])

df

       영어   수학
Dave   60  100
David  70   50

In [33]:
# def func(df_data) :
#     print(type(df_data))
#     print(df_data.index)
#     print(df_data.values)
#     return df_data
def func(df_data) :
    df_data["영어"] = 80
    return df_data

In [36]:
df_func = df.apply(func, axis=0)

In [34]:
df_func = df.apply(func, axis=1)

In [37]:
df_func

       영어   수학
Dave   80  100
David  80   50
영어     80   80

In [39]:
df = pd.DataFrame({
    "성별": ["남", "남", "남"],
    "이름": ["David", "Dave", "Romeo"],
    "수학": [100, 50, 80],
    "국어": [80, 70, 50]
})

df

  성별     이름   수학  국어
0  남  David  100  80
1  남   Dave   50  70
2  남  Romeo   80  50

In [40]:
selected_columns = ["이름", "수학", "국어"]

df = df[selected_columns]
df.groupby("이름").mean()

          수학    국어
이름
Dave    50.0  70.0
David  100.0  80.0
Romeo   80.0  50.0