In [32]:
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
import time
import pandas as pd

service = Service(ChromeDriverManager().install())

options = Options()
# options.add_argument("--headless")
options.add_argument("--window-size=1920x1080")
options.add_argument("--lang=ko_KR")
options.add_argument("--start-maximized")
options.add_argument("--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36")

driver = webdriver.Chrome(service=service, options=options)

query = "contents/genre/concert"
url = f"https://tickets.interpark.com/{query}"

driver.get(url)
time.sleep(2)

try :
    hot_button = driver.find_element(By.XPATH, "//button[contains(text(), '요즘 HOT')]")
    hot_button.click()
    time.sleep(2)
    
except Exception as e :
    print("요즘 HOT 버튼 클릭 실패!!", e)

scroll_pause = 1.5
last_height = driver.execute_script("return document.body.scrollHeight")

#스크롤 했을 때 화이트스페이스 없이 스크롤 높이 값을 그대로 가져가기 위해 사용 안전을 위해
for _ in range(5) :
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(scroll_pause)
    new_height = driver.execute_script("return document.body.scrollHeight")

    if new_height == last_height :
        break
    last_height = new_height

titles = driver.find_elements(By.CSS_SELECTOR, "li.TicketItem_goodsName__Ju76j")
dates = driver.find_elements(By.CSS_SELECTOR, "li.TicketItem_playDate__5ePr2")
places = driver.find_elements(By.CSS_SELECTOR, "li.TicketItem_placeName__ls_9C")
# print(f"{titles}\n, {dates}\n, {place}\n") #확인

group = []
#각각 가져와서 하나의 리스트를 만들때 중첩for문을 사용하지 말고 한번에 할 수 있도록 zip함수 사용
for t, d, p in zip(titles, dates, places) :
    group.append({
        "title":t.text.strip(),
        "date":d.text.strip(),
        "place":p.text.strip(),
    })
print(group) # 확인

driver.quit()

df = pd.DataFrame(group)
df.head()

[{'title': '변진섭 전국투어 콘서트 : 변천사 시즌2', 'date': '2025.02.09 -', 'place': '전국 각 지역'}, {'title': 'RETRO MUSIC CONCERT 〈최재훈×플라워〉', 'date': '2025.08.09, 2025.10.19', 'place': '서울,인천'}, {'title': '옥탑재즈', 'date': '2025.02.14 - 2025.10.24', 'place': '아트센터인천 다목적홀'}, {'title': '2025 심수봉 전국투어 콘서트：꽃길 - 안동', 'date': '2025.09.13', 'place': '안동문화예술의전당 웅부홀'}, {'title': '홍경민 매달리스트 콘서트', 'date': '2025.08.02', 'place': 'SA HALL'}]

                           title                     date          place
0         변진섭 전국투어 콘서트 : 변천사 시즌2             2025.02.09 -        전국 각 지역
1  RETRO MUSIC CONCERT 〈최재훈×플라워〉   2025.08.09, 2025.10.19          서울,인천
2                           옥탑재즈  2025.02.14 - 2025.10.24    아트센터인천 다목적홀
3      2025 심수봉 전국투어 콘서트：꽃길 - 안동               2025.09.13  안동문화예술의전당 웅부홀
4                  홍경민 매달리스트 콘서트               2025.08.02        SA HALL

In [33]:
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
import time
import pandas as pd

service = Service(ChromeDriverManager().install())

options = Options()
# options.add_argument("--headless")
options.add_argument("--window-size=1920x1080")
options.add_argument("--lang=ko_KR")
options.add_argument("--start-maximized")
options.add_argument("--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36")

driver = webdriver.Chrome(service=service, options=options)

query = "contents/genre/concert"
url = f"https://tickets.interpark.com/{query}"

driver.get(url)
time.sleep(2)

try:
    hot_button = driver.find_element(By.XPATH, "//button[contains(text(), '요즘 HOT')]")
    hot_button.click()
    time.sleep(2)
except Exception as e:
    print("요즘 HOT 버튼 클릭 실패!!", e)

group = []
scroll_pause = 1.5
last_height = driver.execute_script("return document.body.scrollHeight")

for _ in range(5):  # 스크롤 횟수 조절 가능
    # 현재 페이지 공연 데이터 수집
    titles = driver.find_elements(By.CSS_SELECTOR, "li.TicketItem_goodsName__Ju76j")
    dates = driver.find_elements(By.CSS_SELECTOR, "li.TicketItem_playDate__5ePr2")
    places = driver.find_elements(By.CSS_SELECTOR, "li.TicketItem_placeName__ls_9C")

    for t, d, p in zip(titles, dates, places):
        data = {
            "title": t.text.strip(),
            "date": d.text.strip(),
            "place": p.text.strip(),
        }
        if data not in group:
            group.append(data)

    # 스크롤 내려서 다음 데이터 로딩
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(scroll_pause)

    new_height = driver.execute_script("return document.body.scrollHeight")
    if new_height == last_height:
        break
    last_height = new_height

print(group)

driver.quit()

df = pd.DataFrame(group)
df.head()

[{'title': 'HOSHI X WOOZI FAN CONCERT ［WARNING］ - SEOUL', 'date': '2025.07.11 - 2025.08.24', 'place': '서울, 부산, 광주'}, {'title': '2025 AKMU STANDING CONCERT ［악동들］', 'date': '2025.08.08 - 2025.08.24', 'place': '명화라이브홀'}, {'title': '2025 현역가왕2 전국투어', 'date': '2025.04.18 ~', 'place': '전국투어'}, {'title': '2025 실리카겔 단독공연 〈Syn. THE. Size X〉', 'date': '2025.08.30 - 2025.08.31', 'place': '킨텍스 1 전시장 1홀'}, {'title': '2025 TEEN TOP WE GONNA ROCK IT DROP IT TOP IT HEY DON＇T STOP IT POP IT X 2 LIVE', 'date': '2025.08.23 - 2025.08.24', 'place': '신한카드 SOL페이 스퀘어 라이브홀'}, {'title': '경기인디뮤직페스티벌 2025 - 화성', 'date': '2025.09.20 - 2025.09.21', 'place': '경기도 화성 정조효공원'}, {'title': 'ONE UNIVERSE FESTIVAL 2025 프리세일 티켓', 'date': '2025.08.15 - 2025.08.16', 'place': '서울대공원 주차광장'}, {'title': '〈미스터트롯3〉 전국투어 콘서트', 'date': '2025.03.29 -', 'place': '전국 각 지역'}, {'title': '2025 이상이 팬미팅 〈이상입니다〉', 'date': '2025.08.09', 'place': '신한카드 SOL페이 스퀘어 라이브홀'}, {'title': '허용별 콘서트 : 보컬 전쟁 시즌2', 'date': '2025.05.10 ~', 'place': '전국 각 지역'}, {'title': '2025 데미소다 콘서트, DEMI-CON!', 'date': '2025.08.16', 'place': '블루스퀘어 SOL트래블홀'}, {'title': 'Jayci yucca 단독 공연 The Last Boy In The Class 3', 'date': '2025.08.16', 'place': '무신사 개러지'}, {'title': '더 로즈(The Rose) Once Upon A WRLD Tour in Seoul', 'date': '2025.08.30', 'place': '블루스퀘어 SOL트래블홀'}, {'title': '2025 Asia Top Artist Festival', 'date': '2025.09.27 - 2025.09.28', 'place': '난지한강공원'}, {'title': '2025 RESCENE 1st FAN-CON［Project 326］', 'date': '2025.08.09', 'place': '성신여자대학교 운정그린캠퍼스 대강당'}]

,title,date,place
0,HOSHI X WOOZI FAN CONCERT ［WARNING］ - SEOUL,2025.07.11 - 2025.08.24,"서울, 부산, 광주"
1,2025 AKMU STANDING CONCERT ［악동들］,2025.08.08 - 2025.08.24,명화라이브홀
2,2025 현역가왕2 전국투어,2025.04.18 ~,전국투어
3,2025 실리카겔 단독공연 〈Syn. THE. Size X〉,2025.08.30 - 2025.08.31,킨텍스 1 전시장 1홀
4,2025 TEEN TOP WE GONNA ROCK IT DROP IT TOP IT ...,2025.08.23 - 2025.08.24,신한카드 SOL페이 스퀘어 라이브홀

In [23]:
pip install pymysql

Requirement already satisfied: pymysql in c:\users\user\anaconda3\lib\site-packages (1.1.1)
Note: you may need to restart the kernel to use updated packages.

In [29]:
import pymysql

#접속할 정보값을 conn이라는 변수안에 pymysql을 이용해서 connect함수를 통해 정보를 넣어준다.
conn = pymysql.connect(
    host='localhost',
    user='root',
    password='',
    db='interpark',
    charset='utf8mb4'
)

#콘이라는 객체한테 커서함수를 이용해서 뭔가 실행할 수 있도록
cursor = conn.cursor()

for _, row in df.iterrows() : #iterrows함수추출해온 데이터를 각각의 행을 찾아오는 역할(enumerate 처럼 인자값을 가져오지만 안써도됨)
    insert_sql = """
    INSERT INTO performances (title, date_range, place)
    VALUES (%s, %s, %s)
    """
    cursor.execute(insert_sql, (row['title'], row['date'], row['place']))

conn.commit()  # 변경사항 커밋
cursor.close()
conn.close()

In [8]:
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
import time
import pandas as pd

service = Service(ChromeDriverManager().install())

options = Options()
# options.add_argument("--headless")
options.add_argument("--window-size=1920x1080")
options.add_argument("--lang=ko_KR")
options.add_argument("--start-maximized")
options.add_argument("--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36")

driver = webdriver.Chrome(service=service, options=options)

query = "contents/genre/concert"
url = f"https://tickets.interpark.com/{query}"

driver.get(url)
time.sleep(2)

try :
    hot_button = driver.find_element(By.XPATH, "//button[contains(text(), '요즘 HOT')]")
    hot_button.click()
    time.sleep(2)
    
except Exception as e :
    print("요즘 HOT 버튼 클릭 실패!!", e)

title_list = driver.find_elements(By.XPATH , "//*[contains (@class, 'ProductList_contents')]")

for i, title_list in enumerate(title_list,1) :
    title = title_list.find_elements(By.XPATH, ".//li")[0].text
    date = title_list.find_elements(By.XPATH, ".//li")[2].text
    print(f"{i}: 제목 : {title} 날짜 :{date}\n")

time.sleep(2)

driver.quit()

1: 제목 : HOSHI X WOOZI FAN CONCERT ［WARNING］ - SEOUL 날짜 :2025.07.11 - 2025.08.24